In [1]:
#pragma nodebook off
#Use nodebook for better reproducibility https://github.com/uoa-eResearch/nodebook
%reload_ext nodebook.ipython
%nodebook disk nodebook_cache

In [ ]:
import geopandas as gpd
import pandas as pd
pd.set_option('display.max_columns', None)
import os
os.listdir("input")

['statsnzstatistical-area-2-2018-generalised-FGDB.zip',
 'statsnzstatistical-area-2-2018-generalised-FGDB.zip:Zone.Identifier',
 'statsnzstatistical-area-2-2020-generalised-FGDB.zip',
 'IMD2018.zip']

In [ ]:
imd = gpd.read_file("input/IMD2018.zip")
imd = imd.set_index("DZ2018")
imd

,Census_Pop,Count_MB18,dhb2015_co,dhb2015_na,ged2020num,ged2020nam,ta2020code,ta2020name,regc2020co,regc2020na,Rank_IMD18,Dec_IMD18,Rank_Emplo,Decile_Emp,Rank_Incom,Decile_Inc,Rank_Crime,Decile_Cri,Rank_Housi,Decile_Hou,Rank_Healt,Decile_Hea,Rank_Educa,Decile_Edu,Rank_Acces,Decile_Acc,RnkIMDNoEm,DecIMDNoEm,RnkIMDNoIn,DecIMDNoIn,RnkIMDNoCr,DecIMDNoCr,RnkIMDNoHo,DecIMDNoHo,RnkIMDNoHe,DecIMDNoHe,RnkIMDNoEd,DecIMDNoEd,RnkIMDNoAc,DecIMDNoAc,geometry
DZ2018,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100001,1134,16,1,Northland,32,Northland,1,Far North District,1,Northland Region,5568,10,5657.0,10,4968,9,3171,6,5446,9,3552,6,6076,10,6142,10,5514,9,5776,10,5607,10,5560,9,5688,10,5322,9,5508,9,"MULTIPOLYGON (((1614004.138 6153881.775, 16140..."
100002,684,9,1,Northland,32,Northland,1,Far North District,1,Northland Region,5253,9,5817.5,10,4762,8,5684,10,3477,6,2745,5,5165,9,5684,10,4731,8,5425,9,5193,9,5354,9,5432,9,5221,9,5200,9,"POLYGON ((1614544.387 6108021.774, 1614449.676..."
100003,615,12,1,Northland,32,Northland,1,Far North District,1,Northland Region,5507,9,5588.0,10,5524,9,3887,7,5290,9,4261,7,5492,9,5642,10,5458,9,5487,9,5527,9,5517,9,5578,10,5478,9,5482,9,"POLYGON ((1615749.571 6109742.666, 1615453.989..."
100004,870,13,1,Northland,32,Northland,1,Far North District,1,Northland Region,4878,8,5535.5,9,4485,8,4015,7,3672,6,2336,4,5067,9,6026,10,4402,8,5049,9,4915,8,4965,9,5115,9,4825,8,4789,8,"POLYGON ((1603784.979 6151770.852, 1603785.748..."
100005,621,10,1,Northland,32,Northland,1,Far North District,1,Northland Region,4821,8,5765.0,10,4227,7,4378,8,3897,7,1089,2,4364,8,5673,10,3908,7,5045,9,4831,8,4881,8,5113,9,4872,8,4761,8,"POLYGON ((1619739.245 6130409.975, 1619741.669..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7602080,501,7,2,Waitemata,18,Kaipara ki Mahurangi,76,Auckland,2,Auckland Region,560,1,149.5,1,1766,3,2318,4,391,1,1819,3,907,2,4999,9,903,2,300,1,602,1,748,2,551,1,656,2,520,1,"POLYGON ((1752669.457 5976848.219, 1752686.046..."
7602081,573,3,3,Auckland,1,Auckland Central,76,Auckland,2,Auckland Region,3425,6,4488.5,8,1988,4,3961,7,5512,9,2967,5,1387,3,50,1,2718,5,3931,7,3417,6,2956,5,3604,6,3728,7,3498,6,"POLYGON ((1757208.013 5919603.375, 1757168.668..."
7602082,570,4,3,Auckland,1,Auckland Central,76,Auckland,2,Auckland Region,2377,4,1635.5,3,1363,3,5883,10,5766,10,368,1,1373,3,14,1,2737,5,2822,5,1849,3,1380,3,2812,5,2598,5,2489,5,"POLYGON ((1757280.243 5919465.450, 1757233.171..."
7602083,585,7,4,Counties Manukau,39,Port Waikato,76,Auckland,2,Auckland Region,4723,8,4426.0,8,4807,8,4605,8,4022,7,4707,8,5174,9,945,2,4860,8,4647,8,4720,8,4759,8,4694,8,4613,8,4741,8,"POLYGON ((1769163.555 5882256.460, 1769182.576..."
7602084,528,12,4,Counties Manukau,39,Port Waikato,76,Auckland,2,Auckland Region,4367,8,1395.0,3,4570,8,6153,10,4464,8,4892,8,4903,8,55,1,5052,9,4213,7,4048,7,4331,8,4248,7,4239,7,4409,8,"POLYGON ((1769176.932 5881753.145, 1769168.298..."

In [ ]:
for col in imd.columns[imd.columns.str.startswith("Rank_")]:
    imd[f"Census_Pop*{col}"] = imd.Census_Pop * imd[col]
imd = imd[list(imd.columns[imd.columns.str.startswith("Census_Pop")]) + ["geometry"]]
imd

,Census_Pop,Census_Pop*Rank_IMD18,Census_Pop*Rank_Emplo,Census_Pop*Rank_Incom,Census_Pop*Rank_Crime,Census_Pop*Rank_Housi,Census_Pop*Rank_Healt,Census_Pop*Rank_Educa,Census_Pop*Rank_Acces,geometry
DZ2018,,,,,,,,,,
100001,1134,6314112,6415038.0,5633712,3595914,6175764,4027968,6890184,6965028,"MULTIPOLYGON (((1614004.138 6153881.775, 16140..."
100002,684,3593052,3979170.0,3257208,3887856,2378268,1877580,3532860,3887856,"POLYGON ((1614544.387 6108021.774, 1614449.676..."
100003,615,3386805,3436620.0,3397260,2390505,3253350,2620515,3377580,3469830,"POLYGON ((1615749.571 6109742.666, 1615453.989..."
100004,870,4243860,4815885.0,3901950,3493050,3194640,2032320,4408290,5242620,"POLYGON ((1603784.979 6151770.852, 1603785.748..."
100005,621,2993841,3580065.0,2624967,2718738,2420037,676269,2710044,3522933,"POLYGON ((1619739.245 6130409.975, 1619741.669..."
...,...,...,...,...,...,...,...,...,...,...
7602080,501,280560,74899.5,884766,1161318,195891,911319,454407,2504499,"POLYGON ((1752669.457 5976848.219, 1752686.046..."
7602081,573,1962525,2571910.5,1139124,2269653,3158376,1700091,794751,28650,"POLYGON ((1757208.013 5919603.375, 1757168.668..."
7602082,570,1354890,932235.0,776910,3353310,3286620,209760,782610,7980,"POLYGON ((1757280.243 5919465.450, 1757233.171..."
7602083,585,2762955,2589210.0,2812095,2693925,2352870,2753595,3026790,552825,"POLYGON ((1769163.555 5882256.460, 1769182.576..."
7602084,528,2305776,736560.0,2412960,3248784,2356992,2582976,2588784,29040,"POLYGON ((1769176.932 5881753.145, 1769168.298..."

In [ ]:
imd.geometry = imd.representative_point()

In [ ]:
sa2 = gpd.read_file("input/statsnzstatistical-area-2-2018-generalised-FGDB.zip!statistical-area-2-2018-generalised.gdb")
sa2 = sa2.set_index("SA22018_V1_00")
sa2

,SA22018_V1_NAME,LAND_AREA_SQ_KM,AREA_SQ_KM,Shape_Length,geometry
SA22018_V1_00,,,,,
190000,Te More,47.922581,47.922581,33420.011116,"MULTIPOLYGON (((1862216.162 5670176.109, 18622..."
100400,Karikari Peninsula,174.180816,174.180816,140012.346179,"MULTIPOLYGON (((1636338.253 6150839.030, 16363..."
100500,Tangonge,177.204343,177.204343,101241.085328,"MULTIPOLYGON (((1622137.152 6120265.782, 16232..."
100900,Rangitihi,84.660427,84.660427,60678.427036,"MULTIPOLYGON (((1626461.006 6119158.300, 16264..."
101000,Oruru-Parapara,103.280728,103.280728,67331.035524,"MULTIPOLYGON (((1638658.179 6128997.443, 16386..."
...,...,...,...,...,...
400011,Bounty Islands,0.000000,0.000000,0.000000,None
400012,Oceanic Snares Islands,0.000000,0.000000,0.000000,None
400013,Snares Islands,0.000000,0.000000,0.000000,None
400014,Oceanic Antipodes Islands,0.000000,0.000000,0.000000,None
400015,Antipodes Islands,0.000000,0.000000,0.000000,None

In [ ]:
joined = gpd.sjoin(sa2, imd)
joined

,SA22018_V1_NAME,LAND_AREA_SQ_KM,AREA_SQ_KM,Shape_Length,geometry,index_right,Census_Pop,Census_Pop*Rank_IMD18,Census_Pop*Rank_Emplo,Census_Pop*Rank_Incom,Census_Pop*Rank_Crime,Census_Pop*Rank_Housi,Census_Pop*Rank_Healt,Census_Pop*Rank_Educa,Census_Pop*Rank_Acces
SA22018_V1_00,,,,,,,,,,,,,,,
100400,Karikari Peninsula,174.180816,174.180816,140012.346179,"MULTIPOLYGON (((1636338.253 6150839.030, 16363...",100023,762,4034790,4487037.0,3974592,2167128,2195322,2921508,3395472,4453890
100400,Karikari Peninsula,174.180816,174.180816,140012.346179,"MULTIPOLYGON (((1636338.253 6150839.030, 16363...",100020,885,4942725,5158222.5,4648905,5300265,1995675,4393140,4852455,5332125
100500,Tangonge,177.204343,177.204343,101241.085328,"MULTIPOLYGON (((1622137.152 6120265.782, 16232...",100002,684,3593052,3979170.0,3257208,3887856,2378268,1877580,3532860,3887856
100500,Tangonge,177.204343,177.204343,101241.085328,"MULTIPOLYGON (((1622137.152 6120265.782, 16232...",100009,822,3476238,3490623.0,3795174,2714244,2539158,3103872,3395682,4228368
100500,Tangonge,177.204343,177.204343,101241.085328,"MULTIPOLYGON (((1622137.152 6120265.782, 16232...",100017,534,2640096,2953821.0,2411010,1399080,1996092,1964586,2860638,2576550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362600,Elizabeth Park,1.030434,1.030434,5084.792826,"MULTIPOLYGON (((1245892.259 4848174.153, 12459...",7500071,651,3497823,3581476.5,3534279,1722546,2527182,3376737,3450951,2341647
181600,Lake Cameron,51.516233,51.516233,46182.545881,"MULTIPOLYGON (((1797736.320 5813528.701, 17981...",1700014,714,1596504,2090235.0,771834,2940966,1146684,2472582,1877820,3702090
181600,Lake Cameron,51.516233,51.516233,46182.545881,"MULTIPOLYGON (((1797736.320 5813528.701, 17981...",1700026,651,1160733,1192632.0,502572,1468005,1609923,3023244,632772,3324657
333600,Craigieburn,3444.102385,3444.102385,325961.578297,"MULTIPOLYGON (((1511215.865 5266196.089, 15112...",6200001,507,1494129,1398559.5,863421,3120585,1600599,584571,1111851,3128190
333700,Torlesse,413.955337,413.955337,117846.474294,"MULTIPOLYGON (((1513576.953 5213946.134, 15136...",6200004,837,1529199,1321623.0,1825497,3305313,1600344,674622,2550339,4929930

In [ ]:
group = joined.groupby(joined.index)

In [ ]:
pop = group["Census_Pop"].sum()

/home/nyou045/git/nodebook/nodebook/pickledict.py:38: FutureWarning: to_msgpack is deprecated and will be removed in a future version.
It is recommended to use pyarrow for on-the-wire transmission of pandas objects.
  return msgpack.ExtType(PANDAS_CODE, obj.to_msgpack())

In [ ]:
pop

/usr/local/lib/python3.8/dist-packages/msgpack/__init__.py:58: FutureWarning: The read_msgpack is deprecated and will be removed in a future version.
It is recommended to use pyarrow for on-the-wire transmission of pandas objects.
  return unpackb(data, **kwargs)

SA22018_V1_00
100100    1134
100200    2889
100400    1647
100500    2040
100600     615
          ...
362800    1149
362900    1296
363000    2283
363100     879
363300    1788
Name: Census_Pop, Length: 2089, dtype: int64

In [ ]:
sa2["Census_Pop"] = pop
sa2

,SA22018_V1_NAME,LAND_AREA_SQ_KM,AREA_SQ_KM,Shape_Length,geometry,Census_Pop
SA22018_V1_00,,,,,,
190000,Te More,47.922581,47.922581,33420.011116,"MULTIPOLYGON (((1862216.162 5670176.109, 18622...",NaN
100400,Karikari Peninsula,174.180816,174.180816,140012.346179,"MULTIPOLYGON (((1636338.253 6150839.030, 16363...",1647.0
100500,Tangonge,177.204343,177.204343,101241.085328,"MULTIPOLYGON (((1622137.152 6120265.782, 16232...",2040.0
100900,Rangitihi,84.660427,84.660427,60678.427036,"MULTIPOLYGON (((1626461.006 6119158.300, 16264...",NaN
101000,Oruru-Parapara,103.280728,103.280728,67331.035524,"MULTIPOLYGON (((1638658.179 6128997.443, 16386...",624.0
...,...,...,...,...,...,...
400011,Bounty Islands,0.000000,0.000000,0.000000,None,NaN
400012,Oceanic Snares Islands,0.000000,0.000000,0.000000,None,NaN
400013,Snares Islands,0.000000,0.000000,0.000000,None,NaN
400014,Oceanic Antipodes Islands,0.000000,0.000000,0.000000,None,NaN
400015,Antipodes Islands,0.000000,0.000000,0.000000,None,NaN

In [ ]:
sa2["Count_DZ2018"] = group.size()

In [ ]:
sa2.Count_DZ2018.value_counts()

2.0     542
3.0     521
4.0     383
1.0     332
5.0     229
6.0      60
7.0      17
8.0       3
9.0       1
13.0      1
Name: Count_DZ2018, dtype: int64

In [ ]:
imd.columns[imd.columns.str.startswith("Census_Pop*")]

Index(['Census_Pop*Rank_IMD18', 'Census_Pop*Rank_Emplo',
       'Census_Pop*Rank_Incom', 'Census_Pop*Rank_Crime',
       'Census_Pop*Rank_Housi', 'Census_Pop*Rank_Healt',
       'Census_Pop*Rank_Educa', 'Census_Pop*Rank_Acces'],
      dtype='object')

In [ ]:
for col in imd.columns[imd.columns.str.startswith("Census_Pop*")]:
    sa2[col.replace("Census_Pop*", "")] = group[col].sum() / pop

/usr/local/lib/python3.8/dist-packages/msgpack/__init__.py:58: FutureWarning: The read_msgpack is deprecated and will be removed in a future version.
It is recommended to use pyarrow for on-the-wire transmission of pandas objects.
  return unpackb(data, **kwargs)
/home/nyou045/git/nodebook/nodebook/pickledict.py:38: FutureWarning: to_msgpack is deprecated and will be removed in a future version.
It is recommended to use pyarrow for on-the-wire transmission of pandas objects.
  return msgpack.ExtType(PANDAS_CODE, obj.to_msgpack())

In [ ]:
sa2

,SA22018_V1_NAME,LAND_AREA_SQ_KM,AREA_SQ_KM,Shape_Length,geometry,Census_Pop,Count_DZ2018,Rank_IMD18,Rank_Emplo,Rank_Incom,Rank_Crime,Rank_Housi,Rank_Healt,Rank_Educa,Rank_Acces
SA22018_V1_00,,,,,,,,,,,,,,,
190000,Te More,47.922581,47.922581,33420.011116,"MULTIPOLYGON (((1862216.162 5670176.109, 18622...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100400,Karikari Peninsula,174.180816,174.180816,140012.346179,"MULTIPOLYGON (((1636338.253 6150839.030, 16363...",1647.0,2.0,5450.828780,5856.259563,5235.881603,4533.936248,2544.624772,4441.194900,5007.848816,5941.721311
100500,Tangonge,177.204343,177.204343,101241.085328,"MULTIPOLYGON (((1622137.152 6120265.782, 16232...",2040.0,3.0,4759.502941,5109.614706,4638.917647,3922.147059,3388.979412,3404.920588,4798.617647,5241.555882
100900,Rangitihi,84.660427,84.660427,60678.427036,"MULTIPOLYGON (((1626461.006 6119158.300, 16264...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101000,Oruru-Parapara,103.280728,103.280728,67331.035524,"MULTIPOLYGON (((1638658.179 6128997.443, 16386...",624.0,1.0,4740.000000,4815.000000,4954.000000,4360.000000,3372.000000,821.000000,5584.000000,5849.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400011,Bounty Islands,0.000000,0.000000,0.000000,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
400012,Oceanic Snares Islands,0.000000,0.000000,0.000000,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
400013,Snares Islands,0.000000,0.000000,0.000000,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
400014,Oceanic Antipodes Islands,0.000000,0.000000,0.000000,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
400015,Antipodes Islands,0.000000,0.000000,0.000000,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
sa2.to_file("output/SA2_2018_with_weighted_average_IMD18.shp.zip", driver='ESRI Shapefile')

<string>:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.